sudo: required
language: c

matrix:
    include:
      - env: postgres=9.4
        addons:
            postgresql: 9.4
            apt:
                packages:
                  - postgresql-server-dev-9.4
        install:
          - sudo make install

      - env: postgres=9.5
        addons:
            postgresql: 9.5
            apt:
                packages:
                  - postgresql-server-dev-9.5
        install:
          - sudo make install

      - env: postgres=9.6
        addons:
            postgresql: 9.6
            apt:
                packages:
                  - postgresql-server-dev-9.6
        install:
          - sudo make install

      - env: postgres=10
        addons:
            postgresql: 10
            apt:
                packages:
                  - postgresql-server-dev-10
        install:
          - sudo make install

      - env: postgres=11
        addons:
            postgresql: 11
            apt:
                packages:
                  - postgresql-11
                  - postgresql-client-11
                  - postgresql-server-dev-11
        install:
          - export PGPORT=5433
          - sudo make install
      - env: postgres=12
        addons:
            postgresql: 12
            apt:
                packages:
                  - postgresql-12
                  - postgresql-client-12
                  - postgresql-server-dev-12
        install:
          - export PGPORT=5433
          - sudo make install

script:
    - make installcheck

after_failure:
  - cat regression.diffs