sudo: required

language: c

services: docker

install:
    - sed -e 's/${PG_VERSION}/'${PG_VERSION}/g Dockerfile.template > Dockerfile
    - docker build . -t tests

script:
    - docker run tests

env:
    - PG_VERSION=12
    - PG_VERSION=11
    - PG_VERSION=10
    - PG_VERSION=9.6
    - PG_VERSION=9.5
    - PG_VERSION=9.4
