-- os_name_op should implement gt;
-- ./spec/country_op_spec.rb:8;
BEGIN;
CREATE EXTENSION country;
SELECT 'uk'::country > 'de'::country;
SELECT 'uk'::country >= 'de'::country;
SELECT NOT('uk'::country < 'de'::country);
SELECT NOT('uk'::country <= 'de'::country);
ROLLBACK;
-- os_name_op should implement lt;
-- ./spec/country_op_spec.rb:15;
BEGIN;
CREATE EXTENSION country;
SELECT 'uk'::country > 'de'::country;
SELECT 'uk'::country >= 'de'::country;
SELECT NOT('uk'::country < 'de'::country);
SELECT NOT('uk'::country <= 'de'::country);
ROLLBACK;
-- os_name_op should implement eq;
-- ./spec/country_op_spec.rb:22;
BEGIN;
CREATE EXTENSION country;
SELECT NOT('de'::country = 'uk'::country);
SELECT 'uk'::country = 'uk'::country;
ROLLBACK;
-- os_name_op should implement neq;
-- ./spec/country_op_spec.rb:27;
BEGIN;
CREATE EXTENSION country;
SELECT 'de'::country != 'uk'::country;
SELECT NOT('uk'::country != 'uk'::country);
ROLLBACK;
