BEGIN;
CREATE EXTENSION country;
SELECT 'uk'::country > 'de'::country;
SELECT 'uk'::country >= 'de'::country;
SELECT NOT('uk'::country < 'de'::country);
SELECT NOT('uk'::country <= 'de'::country);
ROLLBACK;
BEGIN;
CREATE EXTENSION country;
SELECT 'uk'::country > 'de'::country;
SELECT 'uk'::country >= 'de'::country;
SELECT NOT('uk'::country < 'de'::country);
SELECT NOT('uk'::country <= 'de'::country);
ROLLBACK;
BEGIN;
CREATE EXTENSION country;
SELECT NOT('de'::country = 'uk'::country);
SELECT 'uk'::country = 'uk'::country;
ROLLBACK;
BEGIN;
CREATE EXTENSION country;
SELECT 'de'::country != 'uk'::country;
SELECT NOT('uk'::country != 'uk'::country);
ROLLBACK;
