#define AD 'a' << 0 | 'd' << 8
#define AE 'a' << 0 | 'e' << 8
#define AF 'a' << 0 | 'f' << 8
#define AG 'a' << 0 | 'g' << 8
#define AI 'a' << 0 | 'i' << 8
#define AL 'a' << 0 | 'l' << 8
#define AM 'a' << 0 | 'm' << 8
#define AO 'a' << 0 | 'o' << 8
#define AQ 'a' << 0 | 'q' << 8
#define AR 'a' << 0 | 'r' << 8
#define AS 'a' << 0 | 's' << 8
#define AT 'a' << 0 | 't' << 8
#define AU 'a' << 0 | 'u' << 8
#define AW 'a' << 0 | 'w' << 8
#define AX 'a' << 0 | 'x' << 8
#define AZ 'a' << 0 | 'z' << 8
#define BA 'b' << 0 | 'a' << 8
#define BB 'b' << 0 | 'b' << 8
#define BD 'b' << 0 | 'd' << 8
#define BE 'b' << 0 | 'e' << 8
#define BF 'b' << 0 | 'f' << 8
#define BG 'b' << 0 | 'g' << 8
#define BH 'b' << 0 | 'h' << 8
#define BI 'b' << 0 | 'i' << 8
#define BJ 'b' << 0 | 'j' << 8
#define BL 'b' << 0 | 'l' << 8
#define BM 'b' << 0 | 'm' << 8
#define BN 'b' << 0 | 'n' << 8
#define BO 'b' << 0 | 'o' << 8
#define BQ 'b' << 0 | 'q' << 8
#define BR 'b' << 0 | 'r' << 8
#define BS 'b' << 0 | 's' << 8
#define BT 'b' << 0 | 't' << 8
#define BV 'b' << 0 | 'v' << 8
#define BW 'b' << 0 | 'w' << 8
#define BY 'b' << 0 | 'y' << 8
#define BZ 'b' << 0 | 'z' << 8
#define CA 'c' << 0 | 'a' << 8
#define CC 'c' << 0 | 'c' << 8
#define CD 'c' << 0 | 'd' << 8
#define CF 'c' << 0 | 'f' << 8
#define CG 'c' << 0 | 'g' << 8
#define CH 'c' << 0 | 'h' << 8
#define CI 'c' << 0 | 'i' << 8
#define CK 'c' << 0 | 'k' << 8
#define CL 'c' << 0 | 'l' << 8
#define CM 'c' << 0 | 'm' << 8
#define CN 'c' << 0 | 'n' << 8
#define CO 'c' << 0 | 'o' << 8
#define CR 'c' << 0 | 'r' << 8
#define CU 'c' << 0 | 'u' << 8
#define CV 'c' << 0 | 'v' << 8
#define CW 'c' << 0 | 'w' << 8
#define CX 'c' << 0 | 'x' << 8
#define CY 'c' << 0 | 'y' << 8
#define CZ 'c' << 0 | 'z' << 8
#define DE 'd' << 0 | 'e' << 8
#define DJ 'd' << 0 | 'j' << 8
#define DK 'd' << 0 | 'k' << 8
#define DM 'd' << 0 | 'm' << 8
#define DO 'd' << 0 | 'o' << 8
#define DZ 'd' << 0 | 'z' << 8
#define EC 'e' << 0 | 'c' << 8
#define EE 'e' << 0 | 'e' << 8
#define EG 'e' << 0 | 'g' << 8
#define EH 'e' << 0 | 'h' << 8
#define ER 'e' << 0 | 'r' << 8
#define ES 'e' << 0 | 's' << 8
#define ET 'e' << 0 | 't' << 8
#define FI 'f' << 0 | 'i' << 8
#define FJ 'f' << 0 | 'j' << 8
#define FK 'f' << 0 | 'k' << 8
#define FM 'f' << 0 | 'm' << 8
#define FO 'f' << 0 | 'o' << 8
#define FR 'f' << 0 | 'r' << 8
#define GA 'g' << 0 | 'a' << 8
#define GB 'g' << 0 | 'b' << 8
#define GD 'g' << 0 | 'd' << 8
#define GE 'g' << 0 | 'e' << 8
#define GF 'g' << 0 | 'f' << 8
#define GG 'g' << 0 | 'g' << 8
#define GH 'g' << 0 | 'h' << 8
#define GI 'g' << 0 | 'i' << 8
#define GL 'g' << 0 | 'l' << 8
#define GM 'g' << 0 | 'm' << 8
#define GN 'g' << 0 | 'n' << 8
#define GP 'g' << 0 | 'p' << 8
#define GQ 'g' << 0 | 'q' << 8
#define GR 'g' << 0 | 'r' << 8
#define GS 'g' << 0 | 's' << 8
#define GT 'g' << 0 | 't' << 8
#define GU 'g' << 0 | 'u' << 8
#define GW 'g' << 0 | 'w' << 8
#define GY 'g' << 0 | 'y' << 8
#define HK 'h' << 0 | 'k' << 8
#define HM 'h' << 0 | 'm' << 8
#define HN 'h' << 0 | 'n' << 8
#define HR 'h' << 0 | 'r' << 8
#define HT 'h' << 0 | 't' << 8
#define HU 'h' << 0 | 'u' << 8
#define ID 'i' << 0 | 'd' << 8
#define IE 'i' << 0 | 'e' << 8
#define IL 'i' << 0 | 'l' << 8
#define IM 'i' << 0 | 'm' << 8
#define IN 'i' << 0 | 'n' << 8
#define IO 'i' << 0 | 'o' << 8
#define IQ 'i' << 0 | 'q' << 8
#define IR 'i' << 0 | 'r' << 8
#define IS 'i' << 0 | 's' << 8
#define IT 'i' << 0 | 't' << 8
#define JE 'j' << 0 | 'e' << 8
#define JM 'j' << 0 | 'm' << 8
#define JO 'j' << 0 | 'o' << 8
#define JP 'j' << 0 | 'p' << 8
#define KE 'k' << 0 | 'e' << 8
#define KG 'k' << 0 | 'g' << 8
#define KH 'k' << 0 | 'h' << 8
#define KI 'k' << 0 | 'i' << 8
#define KM 'k' << 0 | 'm' << 8
#define KN 'k' << 0 | 'n' << 8
#define KP 'k' << 0 | 'p' << 8
#define KR 'k' << 0 | 'r' << 8
#define KW 'k' << 0 | 'w' << 8
#define KY 'k' << 0 | 'y' << 8
#define KZ 'k' << 0 | 'z' << 8
#define LA 'l' << 0 | 'a' << 8
#define LB 'l' << 0 | 'b' << 8
#define LC 'l' << 0 | 'c' << 8
#define LI 'l' << 0 | 'i' << 8
#define LK 'l' << 0 | 'k' << 8
#define LR 'l' << 0 | 'r' << 8
#define LS 'l' << 0 | 's' << 8
#define LT 'l' << 0 | 't' << 8
#define LU 'l' << 0 | 'u' << 8
#define LV 'l' << 0 | 'v' << 8
#define LY 'l' << 0 | 'y' << 8
#define MA 'm' << 0 | 'a' << 8
#define MC 'm' << 0 | 'c' << 8
#define MD 'm' << 0 | 'd' << 8
#define ME 'm' << 0 | 'e' << 8
#define MF 'm' << 0 | 'f' << 8
#define MG 'm' << 0 | 'g' << 8
#define MH 'm' << 0 | 'h' << 8
#define MK 'm' << 0 | 'k' << 8
#define ML 'm' << 0 | 'l' << 8
#define MM 'm' << 0 | 'm' << 8
#define MN 'm' << 0 | 'n' << 8
#define MO 'm' << 0 | 'o' << 8
#define MP 'm' << 0 | 'p' << 8
#define MQ 'm' << 0 | 'q' << 8
#define MR 'm' << 0 | 'r' << 8
#define MS 'm' << 0 | 's' << 8
#define MT 'm' << 0 | 't' << 8
#define MU 'm' << 0 | 'u' << 8
#define MV 'm' << 0 | 'v' << 8
#define MW 'm' << 0 | 'w' << 8
#define MX 'm' << 0 | 'x' << 8
#define MY 'm' << 0 | 'y' << 8
#define MZ 'm' << 0 | 'z' << 8
#define NA 'n' << 0 | 'a' << 8
#define NC 'n' << 0 | 'c' << 8
#define NE 'n' << 0 | 'e' << 8
#define NF 'n' << 0 | 'f' << 8
#define NG 'n' << 0 | 'g' << 8
#define NI 'n' << 0 | 'i' << 8
#define NL 'n' << 0 | 'l' << 8
#define NO 'n' << 0 | 'o' << 8
#define NP 'n' << 0 | 'p' << 8
#define NR 'n' << 0 | 'r' << 8
#define NU 'n' << 0 | 'u' << 8
#define NZ 'n' << 0 | 'z' << 8
#define OM 'o' << 0 | 'm' << 8
#define PA 'p' << 0 | 'a' << 8
#define PE 'p' << 0 | 'e' << 8
#define PF 'p' << 0 | 'f' << 8
#define PG 'p' << 0 | 'g' << 8
#define PH 'p' << 0 | 'h' << 8
#define PK 'p' << 0 | 'k' << 8
#define PL 'p' << 0 | 'l' << 8
#define PM 'p' << 0 | 'm' << 8
#define PN 'p' << 0 | 'n' << 8
#define PR 'p' << 0 | 'r' << 8
#define PS 'p' << 0 | 's' << 8
#define PT 'p' << 0 | 't' << 8
#define PW 'p' << 0 | 'w' << 8
#define PY 'p' << 0 | 'y' << 8
#define QA 'q' << 0 | 'a' << 8
#define RE 'r' << 0 | 'e' << 8
#define RO 'r' << 0 | 'o' << 8
#define RS 'r' << 0 | 's' << 8
#define RU 'r' << 0 | 'u' << 8
#define RW 'r' << 0 | 'w' << 8
#define SA 's' << 0 | 'a' << 8
#define SB 's' << 0 | 'b' << 8
#define SC 's' << 0 | 'c' << 8
#define SD 's' << 0 | 'd' << 8
#define SE 's' << 0 | 'e' << 8
#define SG 's' << 0 | 'g' << 8
#define SH 's' << 0 | 'h' << 8
#define SI 's' << 0 | 'i' << 8
#define SJ 's' << 0 | 'j' << 8
#define SK 's' << 0 | 'k' << 8
#define SL 's' << 0 | 'l' << 8
#define SM 's' << 0 | 'm' << 8
#define SN 's' << 0 | 'n' << 8
#define SO 's' << 0 | 'o' << 8
#define SR 's' << 0 | 'r' << 8
#define SS 's' << 0 | 's' << 8
#define ST 's' << 0 | 't' << 8
#define SV 's' << 0 | 'v' << 8
#define SX 's' << 0 | 'x' << 8
#define SY 's' << 0 | 'y' << 8
#define SZ 's' << 0 | 'z' << 8
#define TC 't' << 0 | 'c' << 8
#define TD 't' << 0 | 'd' << 8
#define TF 't' << 0 | 'f' << 8
#define TG 't' << 0 | 'g' << 8
#define TH 't' << 0 | 'h' << 8
#define TJ 't' << 0 | 'j' << 8
#define TK 't' << 0 | 'k' << 8
#define TL 't' << 0 | 'l' << 8
#define TM 't' << 0 | 'm' << 8
#define TN 't' << 0 | 'n' << 8
#define TO 't' << 0 | 'o' << 8
#define TR 't' << 0 | 'r' << 8
#define TT 't' << 0 | 't' << 8
#define TV 't' << 0 | 'v' << 8
#define TW 't' << 0 | 'w' << 8
#define TZ 't' << 0 | 'z' << 8
#define UA 'u' << 0 | 'a' << 8
#define UG 'u' << 0 | 'g' << 8
#define UK 'u' << 0 | 'k' << 8
#define UM 'u' << 0 | 'm' << 8
#define US 'u' << 0 | 's' << 8
#define UY 'u' << 0 | 'y' << 8
#define UZ 'u' << 0 | 'z' << 8
#define VA 'v' << 0 | 'a' << 8
#define VC 'v' << 0 | 'c' << 8
#define VE 'v' << 0 | 'e' << 8
#define VG 'v' << 0 | 'g' << 8
#define VI 'v' << 0 | 'i' << 8
#define VN 'v' << 0 | 'n' << 8
#define VU 'v' << 0 | 'u' << 8
#define WF 'w' << 0 | 'f' << 8
#define WS 'w' << 0 | 's' << 8
#define YE 'y' << 0 | 'e' << 8
#define YT 'y' << 0 | 't' << 8
#define ZA 'z' << 0 | 'a' << 8
#define ZM 'z' << 0 | 'm' << 8
#define ZW 'z' << 0 | 'w' << 8
#define XK 'x' << 0 | 'k' << 8
#define ZZ 'z' << 0 | 'z' << 8
