name: CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        pg: [13]
    name: PostgreSQL ${{ matrix.pg }}
    runs-on: ubuntu-latest
    container: zilder/pg-ext-check:0.4
    steps:
      - run: pg-setup ${{ matrix.pg }}
      - uses: actions/checkout@v2
      - run: build-check
      - run: update-check
